export const runtime = 'edge';
import { Header } from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Separator } from '@/components/ui/separator'
import Tags from '@/components/tags'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Header />
          <div className='flex items-center justify-center'>
            <Separator className="w-60 justify-center items-center" />
          </div>
          <div className="container">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            <div className="lg:col-span-9 col-span-1">{children}</div>
            <div className='lg:col-span-3 col-span-1'>
              <div className="lg:sticky relative top-8">
                <Tags />
              </div>

            </div>
          </div>
          </div>
        </div>
      </body>
    </html>
  )
}
